FROM node:alpine


ARG ETHEREUM_ADMIN_PRIVATE_KEY
ENV ETHEREUM_ADMIN_PRIVATE_KEY=$ETHEREUM_ADMIN_PRIVATE_KEY

ARG ETHEREUM_ADMIN_ACCOUNT
ENV ETHEREUM_ADMIN_ACCOUNT=$ETHEREUM_ADMIN_ACCOUNT

ARG WEB3_HTTP_PROVIDER_URL
ENV WEB3_HTTP_PROVIDER_URL=$WEB3_HTTP_PROVIDER_URL

COPY . .

RUN npm install pm2 -g && npm install


CMD ["pm2-runtime", "ecosystem.config.js"]
